### ISSUE TITLE
where are the character-level dependency annotations?

### ISSUE THREAD

**Issue by eugene-yh** [UniversalDependencies/UD_Chinese-PatentChar#1]
The .conllu file in the repository seems to contain only word-level dependency annotations. How do I get the character-level dependency annotations as described in the paper "Character-level Dependency Annotation of Chinese"?

**Comment by nschneid** [comment]
If you are referring to [this paper](https://aclanthology.org/2023.depling-1.5/), it seems that there are both UD and SUD versions of the corpus. The UD version is in terms of words, not characters. The SUD one is here: https://github.com/surfacesyntacticud/SUD_Chinese-PatentChar

**Comment by eugene-yh** [comment]
> If you are referring to [this paper](https://aclanthology.org/2023.depling-1.5/), it seems that there are both UD and SUD versions of the corpus. The UD version is in terms of words, not characters. The SUD one is here: https://github.com/surfacesyntacticud/SUD_Chinese-PatentChar

Thanks! This information really helps.
